version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - data:/data/db
    ports:
      - 27018:27017
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - ./.env.prod
    depends_on:
      - mongo

volumes:
  data:
