services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - data:/data/db

  app:
    image: kishanlalbj/pm:0.5.7
    container_name: password-manager
    ports:
      - 80:80
    env_file:
      - ./.env.prod
    depends_on:
      - mongo

volumes:
  data:
